platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!

target 'RouterServiceExampleApp' do
    pod 'RouterServiceInterface', :path => '../'
    pod 'RouterService', :path => '../'

    pod 'HTTPClientInterface', :path => "./HTTPClientInterface"
    pod 'HTTPClient', :path => "./HTTPClient"

    pod 'FeatureTwoInterface', :path => "./FeatureTwoInterface"
    pod 'FeatureTwo', :path => "./FeatureTwo"

    pod 'FeatureOne', :path => "./FeatureOne"
end

target 'RouterServiceTests' do
    pod 'RouterServiceInterface', :path => '../'
    pod 'RouterService', :path => '../'
end