platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!

target 'RouterServiceExampleApp' do
    pod 'RouterServiceInterface', :path => '../'
    pod 'RouterService', :path => '../'

    pod 'HTTPClientInterface', :path => "./HTTPClientInterface"
    pod 'HTTPClient', :path => "./HTTPClient"

    pod 'FeatureFlagInterface', :path => "./FeatureFlagInterface"
    pod 'FeatureFlag', :path => "./FeatureFlag"

    pod 'FeatureTwoInterface', :path => "./FeatureTwoInterface"
    pod 'FeatureTwo', :path => "./FeatureTwo"

    pod 'FeatureOne', :path => "./FeatureOne"
end